[package]
name = "rusthello"
version = "2.0.0"
authors = ["Enrico Ghiorzi <enrico.ghiorzi@gmail.com>"]

[dependencies]
rand="0.3.*"
probability="0.15.*"

[dependencies.reversi]
version = "0.1.*"
path = "../reversi"
