[package]
name = "ai_brute_mt"
version = "0.1.0"
authors = ["Enrico Ghiorzi <enrico.ghiorzi@gmail.com>"]

[dependencies]
time = "0.1"

[dependencies.rusthello_lib]
version = "0.2"
path = "../rusthello_lib"
