[package]
name = "rusthello_game"
version = "0.3.0"
authors = ["Enrico Ghiorzi <enrico.ghiorzi@gmail.com>"]

[dependencies]
time = "0.1"

[dependencies.rusthello_lib]
version = "0.2"
path = "../rusthello_lib"
